### PR TITLE
Deactivation of connect process and little bug fix

### LINKED ISSUE #1051: Connecting Elements: Usability
While drawing a connection (i.e., first node selected, and currently selecting a second one), a right-click should cancel the operation.

### PR DESCRIPTION
**Pull request by swuest**
Some pull request merged an invalid operation which causes the editor not to load. Fixed that.

Also closes #1051

### CODE REVIEW

File: web/tomato/js/editor.js [hunk 1]
```diff
@@ -4417,13 +4406,44 @@ var Editor = Class.extend({
...
 		for (var i = 0; i < this.listeners.length; i++) this.listeners[i](event);
 	},
+	setWorkspaceContentMenu: function() {
+		var t = this;
+		$('.tomato.workspace').on('contextmenu',function(e) {
+			if(t.mode == Mode.connect || t.mode == Mode.connectOnce) {
+				e.preventDefault();
+				e.stopImmediatePropagation();
+				t.setMode(Mode.select);
+				t.topology.onUpdate();t
```
Comment (dswd) [inline web/tomato/js/editor.js]: bug
