### PR TITLE
Element context menu allows right click

### LINKED ISSUE #997: Right-click in editor right-click menus not working
In the title part of the right-click menus of elements, connections, etc. may be the IDs of these items.
Currently, it is not possible to select of right-click them.

Since IDs have become very long, there must be an easy way to copy these to clipboard.

### PR DESCRIPTION
**Pull request by swuest**
Closes #997

### CODE REVIEW

File: web/tomato/js/jquery.contextMenu.js [hunk 1]
```diff
@@ -204,6 +204,10 @@ var // currently active contextMenu trigger
     handle = {
         // abort anything
         abortevent: function(e){
+        	var $this = $(this);
```
Comment (dswd) [inline web/tomato/js/jquery.contextMenu.js]: Why this variable?

Comment (swuest) [inline web/tomato/js/jquery.contextMenu.js]: I wanted to use the same code style as the original author. It is used in line 208 to check for the correct style class as it references the parts of our context menus which should be able to allow copy-past with standard context menus.
